integration:
  datawarehousereader:
    connectTimeout: 5
    readTimeout: 110
  eventlog:
    connect-timeout: 5
    read-timeout: 10
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
resilience4j:
  circuitbreaker:
    instances:
      datawarehousereader:
        ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
spring:
  application:
    name: api-installedbase
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      client:
        registration:
          datawarehousereader:
            authorization-grant-type: client_credentials
            provider: datawarehousereader
          eventlog:
            authorization-grant-type: client_credentials
            provider: eventlog
springdoc:
  swagger-ui:
    operationsSorter: method
# Prevent duplicate code on setters & getters in sonarcloud 
sonar:
  cpd:
    exclusions: '**/api/model/**'
