integration:
  datawarehousereader:
    connectTimeout: 5
    readTimeout: 20
    url: http://localhost:${wiremock.server.port}/datawarehousereaderMock
spring:
  security:
    oauth2:
      client:
        provider:
          datawarehousereader:
            token-uri: http://localhost:${wiremock.server.port:}/gatewayMock
        registration:
          datawarehousereader:
            client-id: the-client-id
            client-secret: the-client-secret
