integration:
  datawarehousereader:
    connectTimeout: 5
    readTimeout: 20
    url: http://datawarehousereader.url
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.14:///
    username: user
    password: password
  flyway:
    enabled: true
  security:
    oauth2:
      client:
        provider:
          datawarehousereader:
            token-uri: http://token.url
        registration:
          datawarehousereader:
            client-id: the-client-id
            client-secret: the-client-secret
