integration:
  datawarehousereader:
    connectTimeout: 5
    readTimeout: 110
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
resilience4j:
  circuitbreaker:
    instances:
      datawarehousereader:
        ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
spring:
  application:
    name: api-installedbase
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      client:
        registration:
          datawarehousereader:
            authorization-grant-type: client_credentials
            provider: datawarehousereader
springdoc:
  swagger-ui:
    operationsSorter: method
